#! /bin/bash

sudo apt install nodejs
sudo apt install npm

# google cloud
echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

echo "deb https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo tee /usr/share/keyrings/cloud.google.gpg

sudo apt-get update && sudo apt-get install google-cloud-cli

# get main files
wget https://github.com/Leuqas/keepShellAlive/archive/refs/heads/main.zip
sudo apt install unzip
unzip main.zip
# move files to main dir
mv keepShellAlive-main/google\ drive/start.sh ~
mv keepShellAlive-main/google\ drive/stop.sh ~

# run node
node /../install.js