#! /bin/bash

sudo apt install nodejs
sudo apt install npm

mv ~/keepShellAlive-main/google\ drive/start.sh ~
mv ~/keepShellAlive-main/google\ drive/stop.sh ~
npm install prompt-sync
# run setup
clear
echo "                    _                             _____   _              _   _              _   _                                          "
echo "                   | |                           / ____| | |            | | | |     /\     | | (_)                                         "
echo "                   | | __   ___    ___   _ __   | (___   | |__     ___  | | | |    /  \    | |  _  __   __   ___                           "
echo "                   | |/ /  / _ \  / _ \ | '_ \   \___ \  | '_ \   / _ \ | | | |   / /\ \   | | | | \ \ / /  / _ \                          "
echo "                   |   <  |  __/ |  __/ | |_) |  ____) | | | | | |  __/ | | | |  / ____ \  | | | |  \ V /  |  __/                          "
echo "                   |_|\_\  \___|  \___| | .__/  |_____/  |_| |_|  \___| |_| |_| /_/    \_\ |_| |_|   \_/    \___|                          "
echo "                                        | |                                                                                                "
echo "                                        |_|                                                                                                "
sleep 3
echo ""
echo ""
echo ""
node ~/keepShellAlive-main/setup.js
cd ~
cd keepShellAlive-main/
rm -r -d google\ drive/
rm download
cd ../
mv keepShellAlive-main heroku
rm main.zip