#! /bin/bash

sudo apt install nodejs
sudo apt install npm

# google cloud
echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

echo "deb https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo tee /usr/share/keyrings/cloud.google.gpg

sudo apt-get update && sudo apt-get install google-cloud-cli

mv ~/keepShellAlive-main/google\ drive/start.sh ~
mv ~/keepShellAlive-main/google\ drive/stop.sh ~
npm install prompt-sync
# run setup
clear
echo "                    _                             _____   _              _   _              _   _                                          "
echo "                   | |                           / ____| | |            | | | |     /\     | | (_)                                         "
echo "                   | | __   ___    ___   _ __   | (___   | |__     ___  | | | |    /  \    | |  _  __   __   ___                           "
echo "                   | |/ /  / _ \  / _ \ | '_ \   \___ \  | '_ \   / _ \ | | | |   / /\ \   | | | | \ \ / /  / _ \                          "
echo "                   |   <  |  __/ |  __/ | |_) |  ____) | | | | | |  __/ | | | |  / ____ \  | | | |  \ V /  |  __/                          "
echo "                   |_|\_\  \___|  \___| | .__/  |_____/  |_| |_|  \___| |_| |_| /_/    \_\ |_| |_|   \_/    \___|                          "
echo "                                        | |                                                                                                "
echo "                                        |_|                                                                                                "
sleep 3
echo ""
echo ""
echo ""
node ~/keepShellAlive-main/setup.js